version: '3'

services:
  encoder:
    build:
      context: .
      dockerfile: ./encoder.Dockerfile
    volumes:
      - ./.env.local:/var/www/html/.env.local
      - encoder_var:/var/www/html/var

volumes:
  encoder_var:
