version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    image: postgres:${POSTGRES_VERSION:-14}-alpine
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
      POSTGRES_USER: ${POSTGRES_USER:-app}
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data:rw
      # You may use a bind-mounted host directory instead, so that it is harder to accidentally remove the volume and lose all your data!
      # - ./docker/db/data:/var/lib/postgresql/data:rw
###< doctrine/doctrine-bundle ###
  web:
    build:
      context: .
      dockerfile: ./web.Dockerfile
    volumes:
      - ./public/videos:/var/www/html/public/videos
      - ./.env.local:/var/www/html/.env.local

    ports:
      - "8000:80"

  cron:
    build:
      context: .
      dockerfile: ./cron.Dockerfile
    volumes:
      - ./public/videos:/var/www/html/public/videos
      - ./.env.local:/var/www/html/.env.local

  encoder:
    build:
      context: .
      dockerfile: ./encoder.Dockerfile
    volumes:
      - ./.env.local:/var/www/html/.env.local
      - encoder_var:/var/www/html/var

volumes:
###> doctrine/doctrine-bundle ###
  db-data:
  encoder_var:

###< doctrine/doctrine-bundle ###
